---
title: catch
---

<!--
     THIS FILE IS AUTOGENERATED!

     To make changes please edit the corresponding source file under internal/impl/<provider>.
-->



If the result of a target query fails (due to incorrect types, failed parsing, etc) the argument is returned instead.


## Examples
<tabs>
<tab title="Example 0">
	
	<code-block lang="yaml">
		root.doc.id = this.thing.id.string().catch(uuid_v4())
	</code-block>
</tab>
<tab title="Example 1">
	The fallback argument can be a mapping, allowing you to capture the error string and yield structured data back.
	<code-block lang="yaml">
		root.url = this.url.parse_url().catch(err -> {"error":err,"input":this.url})
	</code-block>
</tab>
<tab title="Example 2">
	When the input document is not structured attempting to reference structured fields with `this` will result in an error. Therefore, a convenient way to delete non-structured data is with a catch.
	<code-block lang="yaml">
		root = this.catch(deleted())
	</code-block>
</tab>

</tabs>


